### ISSUE TITLE
tests are failing for currently latest c/go lib versions

### ISSUE THREAD

**Issue by sdeoras** [TileDB-Inc/TileDB-Go#154]
installed c library and then ran go test. i am observing following error message:
c library version: TileDB v2.2.3
go library version: v0.11.4

could you please recommend the combination of c library version and go library version that I should be using?

```
=== RUN   TestEpoch
--- PASS: TestEpoch (0.00s)
=== RUN   TestFragmentInfo
    fragment_info_test.go:145: 
        	Error Trace:	fragment_info_test.go:145
        	Error:      	Not equal: 
        	            	expected: 0x7
        	            	actual  : 0x8
        	Test:       	TestFragmentInfo
--- FAIL: TestFragmentInfo (0.00s)
=== RUN   TestFragmentInfoEncryption
    fragment_info_test.go:263: 
        	Error Trace:	fragment_info_test.go:263
        	Error:      	Not equal: 
        	            	expected: 0x7
        	            	actual  : 0x8
        	Test:       	TestFragmentInfoEncryption
--- FAIL: TestFragmentInfoEncryption (0.00s)
=== RUN   TestGroupCreate
--- PASS: TestGroupCreate (0.00s)
```
tried with go library version v0.11.0  and c lib version at v2.2.3 per this [link](https://github.com/TileDB-Inc/TileDB-Go#compatibility) and see a panic:
```
--- FAIL: ExampleVariableLengthArray (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54f946]

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc0000e1d28, 0xc00032e000, 0x82, 0x13384f1, 0x5a5c20, 0x6dd6f0, 0xc000000180)
	/usr/local/go/src/testing/example.go:89 +0x648
testing.runExample.func2(0xbfff7258aa241850, 0x1f1d038e3, 0x6f7f20, 0xc0001a61b8, 0xc0000a4008, 0xc0001aa1e0, 0xc0000e1d28, 0xc0000e1d58)
	/usr/local/go/src/testing/run_example.go:58 +0x10d
panic(0x5a5c20, 0x6dd6f0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/TileDB-Inc/TileDB-Go.(*Query).ResultBufferElements(0xc0001ac640, 0x0, 0x0, 0x41)
	/home/sdeoras/go/src/github.com/TileDB-Inc/TileDB-Go/query.go:1773 +0x2e6
github.com/TileDB-Inc/TileDB-Go/examples.readVariableLengthArray()
	/home/sdeoras/go/src/github.com/TileDB-Inc/TileDB-Go/examples/variable_length_test.go:247 +0x936
github.com/TileDB-Inc/TileDB-Go/examples.ExampleVariableLengthArray()
	/home/sdeoras/go/src/github.com/TileDB-Inc/TileDB-Go/examples/variable_length_test.go:258 +0x30
testing.runExample(0x5d16d0, 0x1a, 0x5dacb0, 0x5d9b5c, 0xdb, 0x0, 0x0)
	/usr/local/go/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc0000e1ed0, 0x6e2b80, 0x1b, 0x1b, 0xbfff72ec952d54d7)
	/usr/local/go/src/testing/example.go:44 +0x1af
testing.(*M).Run(0xc0000c8000, 0x0)
	/usr/local/go/src/testing/testing.go:1346 +0x273
main.main()
	_testmain.go:95 +0x138
FAIL	github.com/TileDB-Inc/TileDB-Go/examples	8.386s
FAIL
```

**Comment by antalakas** [comment]
@sdeoras please try using TileDB version 2.2.2, which is the latest one using version 7, in 2.2.3 the version was bumped to 8.

The test is not wrong, but its not quite right. The format version will change overtime, so the test should just check that a value is returned and non-zero. Here is a PR where we are changing that

https://github.com/TileDB-Inc/TileDB-Go/pull/155

We are going to cut a release shortly `0.11.5` with the changed test

**Comment by sdeoras** [comment]
awesome, that worked. thanks @antalakas

**Comment by antalakas** [comment]
https://github.com/TileDB-Inc/TileDB-Go/releases/tag/v0.11.5 is released
